// TypeScript port of the Apple serial number decoder.
// Data is loaded from JSON files generated by scripts/generate_decoder_data.py —
// edit tools/decoder-data/modern_models.json or vintage_model_codes.json,
// then run the script to regenerate all platform files at once.

import modernTable from "./modern_models.json";
import vintageJson from "./vintage_model_codes.json";

// ── Types ─────────────────────────────────────────────────────────────────────

export interface VintageSerialResult {
    type: "vintage";
    serial: string;
    factoryCode: string;
    factory?: string;
    year: number;
    week: number;
    modelCode: string;
    modelName?: string;
    warnings: string[];
}

export interface ModernSerialResult {
    type: "modern";
    serial: string;
    format: string;
    factoryCode: string;
    configCode: string;
    modelIdentifier?: string;
    modelName?: string;
    warnings: string[];
}

export type SerialDecodeResult =
    | VintageSerialResult
    | ModernSerialResult
    | { type: "unknown"; message: string }
    | { type: "error"; message: string };

// ── Data ──────────────────────────────────────────────────────────────────────

// modern_models.json is [[code, identifier, name], ...] — build lookup map once
const modernModelCodes: Record<string, [string, string]> = Object.fromEntries(
    (modernTable as [string, string, string][]).map(([code, id, name]) => [code, [id, name]])
);

// vintage_model_codes.json is {code: name | null}
const vintageModelCodes = vintageJson as Record<string, string | null>;

const knownFactories: Record<string, string> = {
    F: "Fremont, California, USA",
    C: "Cork, Ireland",
    CK: "Cork, Ireland",
};

// ── Vintage decoder ───────────────────────────────────────────────────────────

function normalize(input: string): string {
    return input.toUpperCase().replace(/[^A-Z0-9]/g, "");
}

function tryDecodeVintage(normalized: string): VintageSerialResult | null {
    if (normalized.length < 8) return null;

    let pos = 0;
    const warnings: string[] = [];

    // Factory code (1 or 2 chars)
    let factoryCode: string;
    if (normalized.startsWith("CK")) {
        factoryCode = "CK";
        pos = 2;
    } else {
        factoryCode = normalized[0];
        pos = 1;
    }
    const factory = knownFactories[factoryCode];
    if (!factory) {
        warnings.push(`Unknown factory code '${factoryCode}' — location not in lookup table.`);
    }

    // Year char — must be a digit for vintage format
    const yearChar = normalized[pos];
    if (!/^\d$/.test(yearChar)) return null;
    const year = 1980 + parseInt(yearChar, 10);
    pos++;
    if (year >= 1989) {
        warnings.push("Serials from 1989 onward may use a changed Apple serial format; old-style decoding may be ambiguous.");
    }

    // Week (2 digits)
    if (pos + 2 > normalized.length) return null;
    const weekStr = normalized.slice(pos, pos + 2);
    if (!/^\d{2}$/.test(weekStr)) return null;
    const week = parseInt(weekStr, 10);
    pos += 2;
    if (week < 1 || week > 53) {
        warnings.push(`Week ${week} is outside valid range 1–53.`);
    }

    // Production code (3 base-34 chars)
    if (pos + 3 > normalized.length) return null;
    pos += 3;

    // Model code — everything remaining
    const modelCode = normalized.slice(pos);
    const modelName = vintageModelCodes[modelCode] ?? undefined;

    return {
        type: "vintage",
        serial: normalized,
        factoryCode,
        factory,
        year,
        week,
        modelCode,
        modelName: modelName === null ? undefined : modelName,
        warnings,
    };
}

// ── Modern decoder ────────────────────────────────────────────────────────────

function lookupModern(configCode: string): { identifier?: string; name?: string } {
    const entry = modernModelCodes[configCode];
    if (!entry) return {};
    return { identifier: entry[0] || undefined, name: entry[1] || undefined };
}

function decode11(normalized: string): ModernSerialResult {
    const configCode = normalized.slice(-3);
    const factoryCode = normalized.slice(0, 2);
    const { identifier, name } = lookupModern(configCode);
    const warnings: string[] = [];
    if (!identifier && !name) {
        warnings.push(`Config code '${configCode}' not found in modern model database.`);
    }
    return {
        type: "modern",
        serial: normalized,
        format: "11-char (1989–2010)",
        factoryCode,
        configCode,
        modelIdentifier: identifier,
        modelName: name,
        warnings,
    };
}

function decode12(normalized: string): ModernSerialResult {
    const configCode = normalized.slice(-4);
    const factoryCode = normalized.slice(0, 2);
    const { identifier, name } = lookupModern(configCode);
    const warnings: string[] = [];
    if (!identifier && !name) {
        warnings.push(
            `Config code '${configCode}' not found in modern model database. ` +
            `This may be a post-April 2021 serial, which is cryptographically randomized and cannot be decoded.`
        );
    }
    return {
        type: "modern",
        serial: normalized,
        format: "12-char (2010–2021)",
        factoryCode,
        configCode,
        modelIdentifier: identifier,
        modelName: name,
        warnings,
    };
}

// ── Top-level dispatcher ──────────────────────────────────────────────────────

function tryDecodeModern(normalized: string): ModernSerialResult | null {
    switch (normalized.length) {
        case 11: return decode11(normalized);
        case 12: return decode12(normalized);
        default: return null;
    }
}

export function decodeAppleSerial(input: string): SerialDecodeResult {
    const normalized = normalize(input);

    if (normalized.length < 8) {
        return { type: "error", message: "Serial too short (minimum 8 characters after normalization)." };
    }

    const vintage = tryDecodeVintage(normalized);
    const modern = tryDecodeModern(normalized);

    if (vintage && modern) {
        // Both matched — pick the more specific result (modern wins on tie)
        if (vintage.modelName && !modern.modelName) return vintage;
        if (!vintage.modelName && modern.modelName) return modern;
        if (vintage.modelName && modern.modelName) return modern;
        return vintage; // neither has a name — prefer vintage metadata
    }
    if (vintage) return vintage;
    if (modern) return modern;

    return { type: "unknown", message: `Serial length ${normalized.length} does not match any known Apple format.` };
}

// Convenience: return just the model name (or undefined if not identified).
export function decodeSerialModelName(input: string): string | undefined {
    const result = decodeAppleSerial(input);
    if (result.type === "vintage" || result.type === "modern") {
        return result.modelName;
    }
    return undefined;
}
