#!/usr/bin/env python3
"""
Parse OpenCorePkg modelinfo_autogen.h and generate modern_models.swift.

Usage:
    python3 scripts/parse_modelinfo.py path/to/modelinfo_autogen.h \
        > tools/serial-decoder/Sources/SerialDecoderLib/Data/modern_models.swift

Source:
    https://github.com/acidanthera/OpenCorePkg/tree/master/Utilities/macserial
"""

import re
import sys
from pathlib import Path


def parse_enum(content):
    """Extract AppleModel enum values (index -> model identifier like 'MacBook1,1')."""
    match = re.search(r'typedef enum\s+\{([^}]+)\}\s+AppleModel', content, re.DOTALL)
    if not match:
        raise ValueError("AppleModel enum not found")
    body = match.group(1)
    names = [line.strip().rstrip(',') for line in body.splitlines()
             if line.strip() and not line.strip().startswith('//')]
    # Convert enum names like "MacBook11" -> "MacBook1,1" (insert comma before last digit group)
    identifiers = []
    for name in names:
        # Pattern: letters followed by digits optionally followed by digits
        m = re.match(r'^([A-Za-z]+)(\d+)(\d)$', name)
        if m:
            identifiers.append(f"{m.group(1)}{m.group(2)},{m.group(3)}")
        else:
            identifiers.append(name)
    return identifiers


def parse_descriptions(content):
    """Extract AppleModelDesc array (index -> human-readable name string)."""
    match = re.search(
        r'STATIC\s+CONST\s+CHAR8\s+\*\s+AppleModelDesc\s*\[\s*\]\s*=\s*\{([^}]+)\}',
        content, re.DOTALL
    )
    if not match:
        raise ValueError("AppleModelDesc not found")
    body = match.group(1)
    descs = re.findall(r'"([^"]+)"', body)
    return descs


def parse_model_codes(content):
    """
    Extract AppleModelCode array — for each model, an array of valid config code strings.
    Returns list of lists: model_codes[model_index] = [code1, code2, ...]
    """
    # Find the entire AppleModelCode block
    match = re.search(
        r'STATIC\s+CONST\s+CHAR8\s+\*\s+AppleModelCode\s*\[\s*\]\s*\[.*?\]\s*=\s*\{(.+?)\}\s*;',
        content, re.DOTALL
    )
    if not match:
        raise ValueError("AppleModelCode not found")
    body = match.group(1)

    # Each model's codes are in a nested { "CODE1", "CODE2", ..., NULL } block
    model_blocks = re.findall(r'\{([^}]*)\}', body)
    result = []
    for block in model_blocks:
        codes = [c.strip('"') for c in re.findall(r'"([^"]+)"', block)]
        result.append(codes)
    return result


def main():
    if len(sys.argv) < 2:
        print(f"Usage: {sys.argv[0]} <path/to/modelinfo_autogen.h>", file=sys.stderr)
        sys.exit(1)

    path = Path(sys.argv[1])
    content = path.read_text(encoding='utf-8')

    identifiers = parse_enum(content)
    descriptions = parse_descriptions(content)
    model_codes_list = parse_model_codes(content)

    if not (len(identifiers) == len(descriptions) == len(model_codes_list)):
        print(
            f"Warning: count mismatch — identifiers={len(identifiers)}, "
            f"descriptions={len(descriptions)}, code_blocks={len(model_codes_list)}",
            file=sys.stderr
        )

    # Build flat dict: config_code -> (identifier, description)
    mapping: dict[str, tuple[str, str]] = {}
    for i, (ident, desc) in enumerate(zip(identifiers, descriptions)):
        codes = model_codes_list[i] if i < len(model_codes_list) else []
        for code in codes:
            if code not in mapping:
                mapping[code] = (ident, desc)

    # Emit Swift
    print("// Modern Apple Mac model lookup table.")
    print("// Generated by scripts/parse_modelinfo.py from OpenCorePkg modelinfo_autogen.h")
    print("// DO NOT EDIT — re-run the script to regenerate.")
    print()
    print('typealias ModernModelEntry = (identifier: String, name: String)')
    print()
    print('let modernModelCodes: [String: ModernModelEntry] = [')
    for code in sorted(mapping):
        ident, desc = mapping[code]
        # Escape quotes
        safe_code = code.replace('"', '\\"')
        safe_ident = ident.replace('"', '\\"')
        safe_desc = desc.replace('"', '\\"')
        print(f'    "{safe_code}": ("{safe_ident}", "{safe_desc}"),')
    print(']')
    print()
    print('func lookupModernModel(_ configCode: String) -> (String?, String?) {')
    print('    guard let entry = modernModelCodes[configCode] else { return (nil, nil) }')
    print('    return (entry.identifier, entry.name)')
    print('}')


if __name__ == '__main__':
    main()
