#!/usr/bin/env python3
"""
Parse OpenCorePkg modelinfo_autogen.h and generate modern_models.swift.

Usage:
    python3 scripts/parse_modelinfo.py path/to/modelinfo_autogen.h \
        > tools/serial-decoder/Sources/SerialDecoderLib/Data/modern_models.swift

Source:
    https://github.com/acidanthera/OpenCorePkg/tree/master/Utilities/macserial
"""

import re
import sys
from pathlib import Path


def parse_enum(content):
    """Extract AppleModel enum values (index -> model identifier like 'MacBook1,1')."""
    match = re.search(r'typedef enum\s*\{([^}]+)\}', content, re.DOTALL)
    if not match:
        raise ValueError("AppleModel enum not found")
    body = match.group(1)
    names = []
    for line in body.splitlines():
        line = line.strip().rstrip(',')
        if not line or line.startswith('//') or line.startswith('/*'):
            continue
        # Strip inline comments
        line = re.sub(r'\s*//.*$', '', line).strip().rstrip(',').strip()
        if line:
            names.append(line)
    # Convert enum names like "MacBook1_1" -> "MacBook1,1"
    identifiers = []
    for name in names:
        m = re.match(r'^([A-Za-z]+)(\d+)_(\d+)$', name)
        if m:
            identifiers.append(f"{m.group(1)}{m.group(2)},{m.group(3)}")
        else:
            identifiers.append(name)
    return identifiers


def parse_model_codes(content):
    """
    Extract AppleModelCode array — for each model (by index), an array of config code strings.
    Returns list of lists: model_codes[model_index] = [code1, code2, ...]
    """
    match = re.search(
        r'static\s+const\s+char\s+\*AppleModelCode\[\s*\]\[.*?\]\s*=\s*\{(.+?)\}\s*;',
        content, re.DOTALL
    )
    if not match:
        raise ValueError("AppleModelCode not found")
    body = match.group(1)
    # Each model's codes are in a { "CODE1", "CODE2", ..., NULL } block (comment before each)
    model_blocks = re.findall(r'/\*[^*]*\*/\s*\{([^}]*)\}', body)
    if not model_blocks:
        # Fallback: no comments, just find all {} blocks
        model_blocks = re.findall(r'\{([^}]+)\}', body)
    result = []
    for block in model_blocks:
        codes = re.findall(r'"([^"]+)"', block)
        result.append(codes)
    return result


def parse_model_desc(content):
    """
    Extract AppleModelDesc array of {config_code, human_readable_name} pairs.
    Returns dict: config_code -> human_readable_name
    """
    match = re.search(
        r'APPLE_MODEL_DESC\s+AppleModelDesc\s*\[\s*\]\s*=\s*\{(.+?)\}\s*;',
        content, re.DOTALL
    )
    if not match:
        raise ValueError("AppleModelDesc not found")
    body = match.group(1)
    pairs = re.findall(r'\{["\'](.*?)["\'],\s*["\'](.*?)["\']\}', body)
    return {code: name for code, name in pairs}


def main():
    if len(sys.argv) < 2:
        print(f"Usage: {sys.argv[0]} <path/to/modelinfo_autogen.h>", file=sys.stderr)
        sys.exit(1)

    path = Path(sys.argv[1])
    content = path.read_text(encoding='utf-8')

    identifiers = parse_enum(content)
    model_codes_list = parse_model_codes(content)
    desc_map = parse_model_desc(content)  # config_code -> human name

    print(f"Parsed {len(identifiers)} models, {len(model_codes_list)} code blocks, "
          f"{len(desc_map)} desc entries", file=sys.stderr)

    # Build flat dict: config_code -> (identifier, description)
    # Priority: use desc_map for the human name; use model_codes_list for identifier
    code_to_ident: dict[str, str] = {}
    for i, ident in enumerate(identifiers):
        codes = model_codes_list[i] if i < len(model_codes_list) else []
        for code in codes:
            if code not in code_to_ident:
                code_to_ident[code] = ident

    # Merge: all codes from desc_map (human name), with identifier from code_to_ident where known
    all_codes = set(desc_map.keys()) | set(code_to_ident.keys())
    mapping: dict[str, tuple[str, str]] = {}
    for code in all_codes:
        ident = code_to_ident.get(code, "")
        name = desc_map.get(code, "")
        if name:  # only include entries with a human-readable name
            mapping[code] = (ident, name)

    # Emit Swift
    print("// Modern Apple Mac model lookup table.")
    print("// Generated by scripts/parse_modelinfo.py from OpenCorePkg modelinfo_autogen.h")
    print("// DO NOT EDIT — re-run the script to regenerate.")
    print()
    print('typealias ModernModelEntry = (identifier: String, name: String)')
    print()
    print('let modernModelCodes: [String: ModernModelEntry] = [')
    for code in sorted(mapping):
        ident, desc = mapping[code]
        safe_code = code.replace('"', '\\"').replace('\\', '\\\\')
        safe_ident = ident.replace('"', '\\"')
        safe_desc = desc.replace('"', '\\"')
        print(f'    "{safe_code}": ("{safe_ident}", "{safe_desc}"),')
    print(']')
    print()
    print('func lookupModernModel(_ configCode: String) -> (String?, String?) {')
    print('    guard let entry = modernModelCodes[configCode] else { return (nil, nil) }')
    print('    return (entry.identifier, entry.name)')
    print('}')


if __name__ == '__main__':
    main()
